version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest # https://github.com/microsoft/mssql-docker/tree/master/linux/preview
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - mssql:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - mssql-network

volumes:
  mssql:


networks:
  mssql-network:
    driver: bridge
